# Dimesitioal array

## 1D array

In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

l = []

for n in range(1,5):
    array_i =  int(input("enter Array number : "))
    l.append(array_i)
    
print(f" Array is {np.array(l)}")

print(a.ndim)


[1 2 3]
 Array is [5 5 6 4]
1


## 2D Array

In [3]:
arr2 = np.array([[1,2,3,5],[2,34,5,6]])
print(arr2 ,"\n", arr2.ndim)

[[ 1  2  3  5]
 [ 2 34  5  6]] 
 2


## 3D array

In [4]:
arr3 = np.array([[[1,2,3],[4,3,2],[1,6,6]]])
print(arr3 ,"\n", arr3.ndim)

[[[1 2 3]
  [4 3 2]
  [1 6 6]]] 
 3


## HD array

In [5]:
arr_h =  np.array([[[[[[[[[[1,2],[1,2],[1,1],[2,3]]]]]]]]]])
print(arr_h, "\n" , arr_h.ndim)

[[[[[[[[[[1 2]
         [1 2]
         [1 1]
         [2 3]]]]]]]]]] 
 10


# array using function 

## zeros

In [6]:
ar_z = np.zeros(4)
print(ar_z)


[0. 0. 0. 0.]


In [7]:
ar_z = np.zeros((4,5))
print(ar_z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## empty

In [8]:
ar_empty = np.empty((2,2))
print(ar_empty)

[[0. 0.]
 [0. 0.]]


## ones

In [9]:
ar_ones = np.ones((5,5))
print(ar_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Range

In [10]:
ar_r = np.arange(10)
print(ar_r)

[0 1 2 3 4 5 6 7 8 9]


## Digonal

In [11]:
ar_d = np.eye(5,9,1)
print(ar_d , ar_d.ndim)

[[0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]] 2


## line

In [12]:
ar_line = np.linspace(0,20,5)
print(ar_line)

[ 0.  5. 10. 15. 20.]


# create numpy arrays with random numbers

## rand

In [15]:
arr_1 = np.random.rand(5)*5
print(arr_1)

[4.2499443  0.73020734 0.21553747 4.49183518 2.59994766]


## randn

In [17]:
arr_2 = np.random.randn(5)
print(arr_2)

[-0.03938438  1.44035328 -1.75124904  1.22568361 -0.16132642]


## ranf

In [20]:
arr_3 = np.random.ranf(5)
print(arr_3)

[0.38589978 0.31607645 0.19189007 0.81065863 0.57077924]


## randint

In [22]:
arr_4 = np.random.randint(5 , 100 , 10)
print(arr_4)

[59  7 95 27 52 26  6 11  8 61]


# DATA TYPES

In [25]:
var = np.array([1,2])
print(var.dtype)

int64


In [26]:
var = np.array(['a' , 'b'])
print(var.dtype)

<U1


In [26]:
var = np.array([1,'a'])
print(var.dtype)

<U21


In [27]:
var = np.array([1.1])
print(var.dtype)

float64


## convert data types 

In [27]:
x = np.array([1,2,3,4,5])
print(x.dtype)
print(x)

x = np.array([1,2,3], dtype = np.int8)
print(x.dtype)
print(x)

x = np.array([1,2,3], dtype = 'U')
print(x.dtype)
print(x)

x = np.array([1,2,3], dtype = 'f')
print(x.dtype)
print(x)

int64
[1 2 3 4 5]
int8
[1 2 3]
<U1
['1' '2' '3']
float32
[1. 2. 3.]


In [28]:
x = np.array([1,2,3])
new = np.float_(x)
print(new.dtype)
print(new)

new1 = new.astype(int)
print(new1.dtype)
print(new1)

float64
[1. 2. 3.]
int64
[1 2 3]


# shape

In [29]:
var = np.array([[1,2],[3,4]])
print(var)
print(var.shape)

[[1 2]
 [3 4]]
(2, 2)


In [30]:
var1 = np.array([1,2,3,4]).shape

print(var1)

(4,)


# Reshaping

In [31]:
var1 = np.array([1,2,3,4,5,6])
print(var1.reshape(2,3))

print(var1)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [32]:
var1 = np.array([1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7])
var = (var1.reshape(2,4,2))
print(var)
print("\n\n",var.reshape(-1))

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]

 [[9 1]
  [2 3]
  [4 5]
  [6 7]]]


 [1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7]


# Arithmetic Operation in numpy array

In [33]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([1,2,3,4,5,6,7,8])
print(' Add : ', np.add(a,b),'\n\n', 'Subtract : ' , np.subtract(a,b),'\n\n' , 'Multiply : ' ,
      np.multiply(a,b),'\n\n' , 'divide : ', np.divide(a,b),'\n\n' , 'mod : ' ,np.mod(a,b) ,'\n\n',
      'power  : ' , np.power(a,b),'\n\n' , 'reciprocal : ', np.reciprocal(a))


 Add :  [ 2  4  6  8 10 12 14 16] 

 Subtract :  [0 0 0 0 0 0 0 0] 

 Multiply :  [ 1  4  9 16 25 36 49 64] 

 divide :  [1. 1. 1. 1. 1. 1. 1. 1.] 

 mod :  [0 0 0 0 0 0 0 0] 

 power  :  [       1        4       27      256     3125    46656   823543 16777216] 

 reciprocal :  [1 0 0 0 0 0 0 0]


In [34]:
print(a+b)

[ 2  4  6  8 10 12 14 16]


In [63]:
print(a+4)


[ 5  6  7  8  9 10 11 12]


## 2D

In [66]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
print(np.add(a,b))

(3, 3)
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# Other function

In [74]:
x = np.array([1,2,4,5,6,4,1,3])
print("\n\n min : ",np.min(x) ,"\n \n max :",np.max(x)  ,"\n \n sqrt : ",np.sqrt(x) ,"\n \n sin : ",np.sin(x),"\n\n\n cos : ",np.cos(x),"\n\n cumsum : ",np.cumsum(x))



 min :  1 
 
 max : 6 
 
 sqrt :  [1.         1.41421356 2.         2.23606798 2.44948974 2.
 1.         1.73205081] 
 
 sin :  [ 0.84147098  0.90929743 -0.7568025  -0.95892427 -0.2794155  -0.7568025
  0.84147098  0.14112001] 


 cos :  [ 0.54030231 -0.41614684 -0.65364362  0.28366219  0.96017029 -0.65364362
  0.54030231 -0.9899925 ] 

 cumsum :  [ 1  3  7 12 18 22 23 26]


# Broadcasting

In [76]:
a = np.array([1,3,4])
b = np.array([1,2,3,4])
# print(a+b) # error

In [81]:
b = np.array([1,2,3,4])
a = np.array([[1],[2],[3],[4]])
print(np.add(a,b),'\n\n',np.add(a,b).shape)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]] 

 (4, 4)


# Indixing and slicing

In [7]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[0])
print(arr[-2])

1
6


In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1][0])
print(arr[1,0])

4
4


In [12]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:5:2])

[2 4]


# Array interating

In [28]:
arr = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3,2],[4,5,6,8]])
for i in arr:
    print(arr[-i])
print()
for i in arr2:
    print('\n',i)
    for j in i :
        print(j)
    


6
5
4
3
2
1


 [1 2 3 2]
1
2
3
2

 [4 5 6 8]
4
5
6
8


In [34]:
for i in np.ndenumerate(arr2):
    print('\n',i)
# for i in np.nditern(arr2):
#     print('\n',i) // this function removed in numpy
  


 ((0, 0), 1)

 ((0, 1), 2)

 ((0, 2), 3)

 ((0, 3), 2)

 ((1, 0), 4)

 ((1, 1), 5)

 ((1, 2), 6)

 ((1, 3), 8)


# copy v/s view

In [38]:
arr2 = np.array([[1,2,3,2],[4,5,6,8]])
arr = arr2.copy()
arr1 = arr2.view()
print(arr ,'\n\n', arr1 , '\n\n' , arr2)

[[1 2 3 2]
 [4 5 6 8]] 

 [[1 2 3 2]
 [4 5 6 8]] 

 [[1 2 3 2]
 [4 5 6 8]]


In [41]:
arr[0,1]= 41
arr1[0,1]= 45
print(arr ,'\n\n', arr1 , '\n\n' , arr2)

[[ 1 41  3  2]
 [ 4  5  6  8]] 

 [[ 1 45  3  2]
 [ 4  5  6  8]] 

 [[ 1 45  3  2]
 [ 4  5  6  8]]


# join & split 

In [49]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([1,2,3,4,5,6,7,8])
print(np.concatenate((a,b)))


['1' '2' '3' '4' '5' '6' '7' '8' '\n' '1' '2' '3' '4' '5' '6' '7' '8']


In [51]:
a = np.array(['a', 'b','c'])
b = np.array([1,2,3,4])
print(np.concatenate((a,b)))


['a' 'b' 'c' '1' '2' '3' '4']


In [56]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[1,2,3,4],[5,6,7,8]])
print(np.concatenate((a,b) ,axis = 1))

[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


In [83]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([1,2,3,4,5,6,7,8])
print(np.stack((a,b),1))
print()
print(np.dstack((a,b)))
print()
print(np.vstack((a,b)))
print()
print(np.hstack((a,b)))

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]
 [7 7]
 [8 8]]

[[[1 1]
  [2 2]
  [3 3]
  [4 4]
  [5 5]
  [6 6]
  [7 7]
  [8 8]]]

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]

[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]


In [87]:
print(np.array_split(a,3))

a = np.array([[1,2,3,4],[5,6,7,8]])
print(np.array_split(a,3))
print(np.array_split(a,2,1))


[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([], shape=(0, 4), dtype=int64)]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([], shape=(0, 4), dtype=int64)]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


# Search 

In [91]:
print(np.where(a == 2))
b = np.array([1,2,3,4,5,6,7,8])
print(np.where((b%2) == 0))

(array([0]), array([1]))
(array([1, 3, 5, 7]),)


# search sort

In [101]:
b = np.array([1,2,3,7,8])
x = np.searchsorted(b,4)
x1 = np.searchsorted(b,[4,5,6])
print(x,x1)

3 [3 3 3]


#  sort 

In [104]:
b = np.array([1,3,8,1,8,4,0,12,8])
print(np.sort(b))

b = np.array([[1,3,8,1],[8,4,0,12]])
print(np.sort(b))

[ 0  1  1  3  4  8  8  8 12]
[[ 1  1  3  8]
 [ 0  4  8 12]]


# filter

In [119]:
var = np.array(['a', 's', 'h'])
f = [True, False,True ]

result = var[f]

print(result)

['a' 'h']


# shuffle

In [135]:
b = np.array([1,2,3,3,3,6,6,1,7,8])
np.random.shuffle(b)
print(b)

[3 6 6 1 8 3 3 1 2 7]


# unique 

In [137]:
b = np.array([1,2,3,3,3,6,6,1,7,8])
b = np.unique(b , return_index = True , return_counts = True)
print(b)

(array([1, 2, 3, 6, 7, 8]), array([0, 1, 2, 5, 8, 9]), array([2, 1, 3, 2, 1, 1]))


# Resize , Flatten ,Revel 

In [154]:
b = np.array([[1,2,3,3,3],[6,6,1,7,8]])
print(b.flatten('f'))
print(b.flatten('c'))

b = np.array([1, 2, 3, 4, 5,  8])
print(b.ravel('f'))

[1 6 2 6 3 1 3 7 3 8]
[1 2 3 3 3 6 6 1 7 8]
[1 2 3 4 5 8]


# insert &  Delete

In [179]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(np.insert(b ,4 , [4,5,0,45 ]))

print()
x = np.array([[1, 2, 3, 4],[ 5, 6, 7, 8]])
print(np.insert(x ,2 , [4,5,0,45],axis =0))

x = np.array([[1, 2, 3, 4],[ 5, 6, 7, 8]])
x = np.append(x ,[4,5,0,45])
print(x


[ 1  2  3  4  4  5  0 45  5  6  7  8]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 4  5  0 45]]
[ 1  2  3  4  5  6  7  8  4  5  0 45]


In [186]:
D =  np.delete(b , [0,1,4])
print(D)

[3 4 6 7 8]


# Matrix

In [194]:
m = np.matrix([[1,2],[3,4]])
n = np.matrix([[1,2],[3,4]])
print(m ,'\n\n', n)
type(m)

[[1 2]
 [3 4]] 

 [[1 2]
 [3 4]]


numpy.matrix

In [196]:
print(m+n)
print(m*n)
print(m.dot(n))

[[2 4]
 [6 8]]
[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


# Matrix Function 

## Transpose , Swapaxes , Inverse , Power , Determinate

In [198]:
m = np.matrix([[1,2],[3,4]])
print(m , '\n')
print(np.transpose(m))

[[1 2]
 [3 4]] 

[[1 3]
 [2 4]]


In [202]:
print(np.swapaxes(m, 1 , 0))

[[1 3]
 [2 4]]


In [203]:
print(np.linalg.inv(m))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [207]:
print(np.linalg.matrix_power(m,2))
print(np.linalg.matrix_power(m,0))
print(np.linalg.matrix_power(m,-2))

[[ 7 10]
 [15 22]]
[[1 0]
 [0 1]]
[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [214]:
m = np.matrix([[8,2],[8,8]])
print(np.linalg.det(m))


47.999999999999986
